---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: debian-7.3

suites:
  - name: default
    run_list:
      - recipe[phabricator::default]
    attributes:
  - name: arcanist
    run_list:
      - recipe[phabricator::arcanist]
    attributes:
